name: CI

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.2']

    # services:
    #   postgres:
    #     image: postgres:11.5
    #     ports: ["5432:5432"]
    #     options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      # - name: Install PostgreSQL 11 client
      #   run: |
      #     sudo apt-get -yqq install libpq-dev
      # - uses: actions/cache@v1
      #   with:
      #     path: ./skipper/vendor/bundle
      #     key: ${{ runner.os }}-bundle-${{ hashFiles('**/Gemfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-bundle-
    - name: Build App
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
            bin/rails db:setup
            yarn
    - name: Run Tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
        run: rspec
