name: CI Pipeline

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: 3.2.2
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Build App
      env:
        RAILS_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        RAILS_ENV: test
      run: |
            echo $RAILS_KEY > config/master.key
            bundle config path vendor/bundle
            bundle install --jobs 4 --retry 3
            bin/rails db:setup
            yarn
    - name: Run Tests
      env:
        RAILS_ENV: test
      run: bin/rails spec
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      # Add or replace any other lints here
      - name: Install rubocop, brakeman, and bundler-audit
        run: |
          gem install rubocop rubocop-rspec rubocop-discourse brakeman bundler-audit
      - name: Security audit dependencies
        run: bundle-audit --update
      - name: Security audit application code
        run: brakeman -q -w2
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
